- modules/hdbt_admin_tools/hdbt_admin_tools.module
- modules/hdbt_admin_tools/src/Form/SiteSettings.php
How to test (if you have no setup etc.):
- `composer create-project City-of-Helsinki/drupal-helfi-platform:dev-main hel-platform --no-interaction --repository https://repository.drupal.hel.ninja/`
- Switch to corresponding branches: 
- `composer require drupal/hdbt_admin:dev-UHF-193_invalidate_caches`
- Run `make new`
- Log in to the site.
- In an incognito window or another browser load https://hel-platform.docker.sh/sv
- In logged in window go to https://hel-platform.docker.sh/fi/admin/tools/site-settings/translate/sv/add
- Add translations to each field what you can translate
- Save the changes
- Switch to the incognito window and reload the page (no hard reload or such thing)
- Make sure your translations have appeared to the site.
> UHF-193 Cache invalidation

- modules/hdbt_admin_editorial/src/Plugin/Field/FieldWidget/LinkTargetFieldWidget.php
Fixed whitescreen caused by invalid parameter on function call
Use any existing site
1. `composer require drupal/hdbt_admin:dev-UHF-3160_listoflinks_fix`
2. make drush-cr
3. Go to /node/8/edit
(open inspector, look for ajax errors)
4. Open the first item in list of links paragraph
5. Change the link from /node/1 to (f.ex) /node/8
6. Save
- Expected result: no whitescreen, no ajax errors, the link on the page is ok.
7. Go back to edit
8. Set external link as the first link in list of links paragraph
9. Save
10. Check the first link on the page, it should be OK
- Expected result: no whitescreen, no ajax errors, the link on the page is ok.
> UHF-3160 List of links fix

- modules/hdbt_admin_editorial/assets/js/plugins/quote/dialogs/quote.js
Related to https://github.com/City-of-Helsinki/drupal-hdbt/pull/220 and https://github.com/City-of-Helsinki/drupal-helfi-platform-config/pull/233
* Fixed quote elements to be [more semantic](http://html5doctor.com/cite-and-blockquote-reloaded/#:~:text=Example%20of%20footer%20and%20cite%20used%20inside%20a%20blockquote)
* Get this branch
* Also get this branch: https://github.com/City-of-Helsinki/drupal-helfi-platform-config/pull/233
* Check that quotes have now `<blockquote>` and `<cite>`
> Fix quote elements to be more semantic

- modules/hdbt_admin_editorial/src/Plugin/Field/FieldWidget/LinkTargetFieldWidget.php
Make sure all required modules are up to date:
- `composer update drupal/helfi_proxy drupal/helfi_api_base` (proxy should be at least version 2.1.0 and api_base should be 2.0.1)
- `drush updb`
Add a link to a non-existent page with same domain using CKEditor. For example if you're testing this on SOTE: `https://helfi-sote.docker.so/rekry/test`. 
The link should be converted to `/rekry/test` (the domain part is removed) and it should *not* contain a proxy path (like `/fi/sosiaali-ja-terveyspalvelut`).
> UHF-4227: Removed hdbt linkit customizations since we process links in api_base module now

- modules/hdbt_admin_tools/src/Form/SiteSettings.php
Saving of the site settings didn't work correctly before. Fixed that so that koro, color-palette and icon are correctly saved and applied.
* Refactored site settings form.
* Check instructions from https://github.com/City-of-Helsinki/drupal-hdbt/pull/261
* Check instructions from https://github.com/City-of-Helsinki/drupal-hdbt/pull/261
* https://github.com/City-of-Helsinki/drupal-hdbt/pull/261
> UHF-4064: Refactored site settings form.

- composer.json
Locked gin theme to 3.0.0-alpha37 as it needs some TLC before updating to beta.
* `make fresh`
* `composer require drupal/hdbt_admin:dev-UHF-X_gin_theme_lock`
* Check your instance composer.lock for drupal/gin theme and make sure it's  3.0.0-alpha37
> UHF-X Gin theme lock

- hdbt_admin.libraries.yml
* `composer require drupal/hdbt_admin:dev-UHF-4983_sortable`
* Test the announcement creation for TPR units / services
> Added Sortable as a dependency for the overridden select2 library

- config/install/block.block.language_switcher_admin.yml
- templates/page/page--group.html.twig
Fix layout issue on group content creation from where the sidebar would go under content when adding new content to group.
* Changed the page--group template to extend correct template and removed the language switcher from the group content creation page since it isn't available on the regular content creation page either.
* You can only test this in KASKO since the group functionality is enabled only there currently.
* `make fresh`
* Update the hdbt_admin and helfi_platform_config
* `composer require drupal/hdbt_admin:dev-UHF-4847_admin_theme_fixes_for_groups`
* `composer require drupal/helfi_platform_config:dev-UHF-4847_admin_theme_fixes_for_groups`
* Run `make drush-updb && make drush-cr`
* Go to …
> UHF-4847: Fix layout issue on group content creation form

- modules/hdbt_admin_editorial/assets/js/linkPluginEnhancements.js
- modules/hdbt_admin_editorial/assets/js/plugins/hds-button/plugin.js
- modules/hdbt_admin_editorial/hdbt_admin_editorial.module
When adding or editing link on ckeditor, prevent title-attribute from being autocompleted in any situation
* Removed default value from link's title-attribute field's definition
* (Bonus bug fix) Prevent the actual title field from being autocompleted with invalid value if multiple links are created one after another without page load in between. 
* Can be tested in any environment
* `make fresh`
* `composer require drupal/hdbt_admin:dev-UHF-2915_ckeditor_link_title_attribute_default_value`
* Go to any content (edit or create new)
* Create or edit any text-paragraph with ckeditor in it
* Add a link by clicking the link button in ckeditor header: add …
> UHF-2915 ckeditor link title attribute default value

- modules/hdbt_admin_editorial/hdbt_admin_editorial.install
- modules/hdbt_admin_editorial/hdbt_admin_editorial.module
* Fixed CKEditor link targets when saving the link
* Added an update hook to fix all wrongly targeted links from all text_long fields ( `target="0"` )
* `make fresh`
* `composer require drupal/hdbt_admin:dev-UHF-5992_link_target`
* Go to edit any page with CKEditor
* Add new links with the CKEditor link tool
* Save the page and check the markup for faulty `target="0"`
> UHF-5992: Link target

- modules/hdbt_admin_editorial/hdbt_admin_editorial.module
- modules/hdbt_admin_editorial/hdbt_admin_editorial.routing.yml
- modules/hdbt_admin_editorial/src/Form/UserLoginLink.php
- modules/hdbt_admin_editorial/translations/fi.po
- modules/hdbt_admin_editorial/translations/sv.po
* Created a form for administrator to create one-time login links for Drupal users.
* `make fresh`
* `composer require drupal/hdbt_admin:dev-UHF-6006_user_access`
* `composer require drupal/hdbt:dev-UHF-6006_user_access`
* Login to any instance as Admin user (no UID1)
* It can be done like so: `drush uli --uid=123` - just make sure that the user you're login in with has admin (Pääkäyttäjä) role.
* Once logged in, go to `/admin/people` and select "Update user password" from operations.
* Click on Generate URL and copy the link once the form prints it out.
* Open a new browser or incognito window and paste the URL there. See …
> UHF-6006: User access

- templates/module/helfi_debug/debug-item--robots.html.twig
Added template which shows rebots header status on debug page
Related PR
https://github.com/City-of-Helsinki/drupal-module-helfi-proxy/compare/UHF-5938_robots_debug_page_entry
> UHF-5938: added template for rebots entry

- modules/hdbt_admin_tools/src/Form/SiteSettings.php
Changed placeholder icons to use abstract icons
* Switched the old icons for the abstract icons that design selected.
* `make fresh`
* `composer require drupal/hdbt_admin:dev-UHF-3238_placeholder_icons`
* `composer require drupal/hdbt:dev-UHF-3238_placeholder_icons`
* Go to `/admin/tools/site-settings` and make sure you can select the default icon from the abstract icons like in the screenshot.
* Select one, save the settings and make sure the default icon works correctly.
* https://github.com/City-of-Helsinki/drupal-hdbt/pull/419
> UHF-3238: Changed placeholder icons to use abstract icons

- modules/hdbt_admin_tools/config/install/hdbt_admin_tools.site_settings.yml
- modules/hdbt_admin_tools/config/install/language/fi/hdbt_admin_tools.site_settings.yml
- modules/hdbt_admin_tools/config/schema/hdbt_admin_tools.schema.yml
- modules/hdbt_admin_tools/hdbt_admin_tools.install
- modules/hdbt_admin_tools/hdbt_admin_tools.module
- modules/hdbt_admin_tools/src/Form/SiteSettings.php
Remove footer top content configuration and replace it with a real menu on instances that don't use global navigation.
* Removed footer top content configuration form.
* Removed footer top content configuration form the configuration files.
* Test this feature with Rekry-instance and with one instance that has global navigation enabled like for example Sote-instance.
* `make fresh`
* `composer require drupal/hdbt_admin:dev-UHF-7139_remove_footer_top_content_configuration`
* `composer require drupal/hdbt:dev-UHF-7139_remove_footer_top_content_configuration`
* Update the helfi_navigation
* `composer require drupal/helfi_navigation:dev-UHF-7139_remove_footer_top_content_configuration`
* Run `make drush-cr && make …
> UHF-7139: Remove footer top content configuration

- modules/hdbt_admin_editorial/src/DesignSelectionManager.php
* Update the HDBT admin theme
* `composer require drupal/hdbt_admin:dev-UHF-7126`
> UHF-7126: Run assets through file generator

- modules/hdbt_admin_editorial/hdbt_admin_editorial.info.yml
Robot tests  seems to fail due to missing dependency: https://github.com/City-of-Helsinki/drupal-helfi-platform-config/actions/runs/3427627080/jobs/5710862812
> Added missing hdb_admin_tools dependency

- composer.json
Admin toolbar 2.0 is unsupported.
* Removed `drupal/admin_toolbar` dependency since it's already required by helfi_platform_config module 
* Update the HDBT Admin theme and platform config module
* `composer require drupal/hdbt_admin:dev-UHF-X-update-admin-toolbar drupal/helfi_platform_config:dev-UHF-X-update-admin-toolbar -W`
* https://github.com/City-of-Helsinki/drupal-helfi-platform-config/pull/472
> Remove drupal/admin_toolbar dependency

- composer.json
* Freeze admin toolbar module to 3.3.0 until the [fixed accessibility issue](https://www.drupal.org/node/3286466) has been addressed also in the Gin toolbar module or Gin theme.
* `make fresh`
* `composer require drupal/hdbt_admin:dev-UHF-X_freeze_admin_toolbar_330 -W`
* ![image](https://user-images.githubusercontent.com/1712902/235627946-d7e801be-6c83-4eec-ac2e-7f8ff9a9ef6e.png)
* Here's how it was after the module update
> UHF-X Freeze admin toolbar 3.3.0

- composer.json
This admin_toolbar module was frozen to 3.3.0 due to issue with double arrows: https://www.drupal.org/node/3286466
This has now been fixed so updating to latest version. Also there was a security update that needs to be deployed everywhere.
> UHF-X: Admin toolbar update

- hdbt_admin.theme
"Fix" cookie banner broken styles. Actually hide the cookie banner on admin pages.
Added preprocess hook for hiding the cookie banner on admin pages.
Uses the cookie banner module's built-in strategy for hiding the banner. You can check the `eu_cookie_compliance_page_attachments` function here: https://git.drupalcode.org/project/eu-cookie-compliance/-/blob/8.x-1.x/eu_cookie_compliance.module for more info.
* `make drush uli` in the instance you're going to use for testing
* Open the log-in link in incognito tab
* Go to `https://[your instance]/en/admin/content/media`
* You *should* see cookie banner here (with broken styles)
* Boot up an instance of your choice. Note the preliminary steps above ☝️ 
* Install this feature: `composer require …
> UHF-7426: Hide cookie banner on admin pages

- hdbt_admin.libraries.yml
* Removed mention to Jquery.once as the Select2 library doesn't use jQuery.once
* `make fresh`
* `composer require drupal/hdbt_admin:dev-UHF-8389_core_once`
* Check that features that uses Select 2 still works. For example:
* https://github.com/City-of-Helsinki/drupal-helfi-platform-config/pull/510
[UHF-8389]: https://helsinkisolutionoffice.atlassian.net/browse/UHF-8389?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> UHF-8389: Core once

- README.md
Make commands for compiling the theme were already documented in [City-of-Helsinki/drupal-helfi-platform](https://github.com/City-of-Helsinki/drupal-helfi-platform/blob/main/documentation/build-assets.md) repository. This PR adds description of the commands to this repository so they are easier to find.
* `make fresh`
* `composer require drupal/hdbt:dev-UHF-8510-document-theme-build-commands`
* City-of-Helsinki/drupal-helfi-platform#131
[UHF-8510]: https://helsinkisolutionoffice.atlassian.net/browse/UHF-8510?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> UHF-8510: Document commands for building assets in containers

- hdbt_admin.theme
* https://github.com/City-of-Helsinki/drupal-helfi-etusivu/pull/572
* https://github.com/City-of-Helsinki/drupal-helfi-platform-config/pull/735
* https://github.com/City-of-Helsinki/drupal-hdbt-admin/pull/280
* https://github.com/City-of-Helsinki/drupal-hdbt/pull/945
[UHF-9738]: https://helsinkisolutionoffice.atlassian.net/browse/UHF-9738?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> UHF-9738: Hide content_translation_status published for news articles content type

- composer.json
* Lock Gin version to RC10 until we've checked all possible issues from RC11.
* `make fresh`
* `composer require drupal/hdbt_admin:dev-UHF-X_lock_gin_rc10 -W`
> UHF-X Lock Gin version to RC10

- hdbt_admin.theme
* Don't show a preview button for new node translations.
* When the user clicks the preview button for a new node or a new translation, any paragraphs or other entity references have not yet been saved/created. This is a problem in preview as the preview tries to load the entities or their revisions. It's easier to hide the Preview button for this kind of niche user behaviour than to build an entire function to display unsaved entities.
* `make fresh`
* `composer require drupal/hdbt_admin:dev-UHF-9950`
[UHF-9950]: https://helsinkisolutionoffice.atlassian.net/browse/UHF-9950?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHV …
> UHF-9950 Preview on new translations

- composer.json
- patches/gin-3460390-sidebar-nextsibling-innerhtml-rc11.patch
* Added patch for the gin sidebar issue. See: https://www.drupal.org/project/gin/issues/3460390
* `make fresh`
* `composer require drupal/hdbt_admin:dev-UHF-10892 -W`
* https://github.com/City-of-Helsinki/drupal-infofinland/pull/364
[UHF-10892]: https://helsinkisolutionoffice.atlassian.net/browse/UHF-10892?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> UHF-10892 Gin sidebar

- hdbt_admin.theme
* Removed remnants of `helfi_eu_cookie_compliance` and `eu_cookie_compliance` modules
* `make fresh`
* Update the Helfi Platform config
* `composer require drupal/helfi_platform_config:dev-UHF-10862 drupal/hdbt:dev-UHF-10862 drupal/hdbt_admin:dev-UHF-10862 -W`
* Run `make drush-updb drush-cr`
* https://github.com/City-of-Helsinki/drupal-helfi-platform-config/pull/1036
* https://github.com/City-of-Helsinki/drupal-hdbt/pull/1326
* https://github.com/City-of-Helsinki/drupal-hdbt-admin/pull/340
* https://github.com/City-of-Helsinki/helsinki-paatokset/pull/677
* https://github.com/City-of-Helsinki/hel-fi-drupal-grants/pull/1798
[UHF-10862]: https://helsinkisolutionoffice.atlassian.net/browse/UHF-10862?atlO …
> UHF-10862 Remove obsolete code
