City-of-Helsinki/drupal-hdbt-admin

modules/hdbt_admin_tools/src/Controller/ListController.php

How to test: 
- Check instructions from https://github.com/City-of-Helsinki/drupal-hdbt/pull/27
- When the one above is approved, you may approve this one as well

UHF-242 Modify wave motifs

---

hdbt_admin.theme
modules/hdbt_admin_editorial/hdbt_admin_editorial.module
modules/hdbt_admin_editorial/src/Plugin/Validation/Constraint/HeroImageConstraint.php
modules/hdbt_admin_tools/hdbt_admin_tools.module
modules/hdbt_admin_tools/src/Controller/ListController.php
modules/hdbt_admin_tools/src/Form/SiteSettings.php

How to test: 
- Check instructions from https://github.com/City-of-Helsinki/drupal-hdbt/pull/31
- When the one above is approved, you may approve this one as well

UHF-79 Language switcher

---

modules/hdbt_admin_editorial/assets/js/plugins/hds-button/plugin.js
modules/hdbt_admin_editorial/hdbt_admin_editorial.module
modules/hdbt_admin_editorial/src/Plugin/Field/FieldWidget/LinkTargetFieldWidget.php

How to test:
- Check instructions from https://github.com/City-of-Helsinki/drupal-helfi/pull/72
- When the one above is approved, you may approve this one as well

UHF-927 External link

---

hdbt_admin.theme

UHF-1406: Relative URL

---

modules/hdbt_admin_editorial/hdbt_admin_editorial.info.yml
modules/hdbt_admin_editorial/src/Plugin/Field/FieldWidget/LinkTargetFieldWidget.php
modules/hdbt_admin_editorial/src/Plugin/Field/FieldWidget/LinkTargetIconFieldWidget.php

Check out [THIS PR](https://github.com/City-of-Helsinki/drupal-helfi-platform-config/pull/160). 
(Related to [This site specific branch](https://github.com/City-of-Helsinki/drupal-helfi-sote/tree/UHF-1872_linkit_list_tpr_entities))

UHF-1872 Linkit list TPR entities

---

modules/hdbt_admin_editorial/src/Plugin/Field/FieldWidget/LinkTargetFieldWidget.php

To test this:
- `composer require drupal/hdbt_admin:UHF-2919-dev`
Add a list of links item to any content and add an external link with same domain. For example 'https://helfi-kymp.docker.so/test` and make sure it's not converted to relave (`/test`).

UHF-2919: Don't convert absolute URLs to relative if it links to same domain

---

modules/hdbt_admin_editorial/hdbt_admin_editorial.install

Check instructions from 
https://github.com/City-of-Helsinki/drupal-helfi-platform-config/pull/221

UHF-3474 Color palette

---

hdbt_admin.info.yml
hdbt_admin.theme
translations/fi.po
translations/sv.po

Check instructions from: https://github.com/City-of-Helsinki/drupal-helfi-platform-config/pull/225

UHF-3268 News item

---

modules/hdbt_admin_editorial/hdbt_admin_editorial.info.yml
modules/hdbt_admin_editorial/hdbt_admin_editorial.module
modules/hdbt_admin_editorial/translations/fi.po
modules/hdbt_admin_editorial/translations/sv.po

Check instructions from https://github.com/City-of-Helsinki/drupal-helfi-platform-config/pull/261

UHF-2059 Admin UI translations

---

hdbt_admin.theme

How to test:
1) set up any instance
2) add a new node of any type
3) see that the "Preview" button is missing

UHF-4639: disable preview button on new nodes

---

hdbt_admin.theme
modules/hdbt_admin_editorial/hdbt_admin_editorial.install
modules/hdbt_admin_editorial/hdbt_admin_editorial.module
modules/hdbt_admin_editorial/translations/fi.po
modules/hdbt_admin_editorial/translations/sv.po

Check instructions from 
- https://github.com/City-of-Helsinki/drupal-hdbt/pull/289

UHF-3884 Sidebar

---

modules/hdbt_admin_editorial/hdbt_admin_editorial.install
modules/hdbt_admin_editorial/hdbt_admin_editorial.post_update.php

Moved field installation functions from update to post update.

UHF-3884: Sidebar fix 

---

templates/module/helfi_debug/debug-item--tunnistamo.html.twig

Added tunnistamo credential status to debug page
* Sheck [helfi_tunnistamo](https://github.com/City-of-Helsinki/drupal-module-helfi-tunnistamo/pulls) module

Uhf 5450 tunnistamo debug

---

modules/select2_icon/src/Plugin/Field/FieldType/Select2Icon.php

* Added invalid argument exception check to the icons path in select2_icon load_icons method.
* `make fresh`
* `composer require drupal/hdbt_admin:dev-UHF-X_select2_icon_missing_json`
* Change the `path_to_json` in `conf/cmi/select2_icon.settings.yml` to something what doesn't exists
* Run `make drush-cim drush-cr`
* Go to create a landing page and try to add Hero. Check that there's an error message and that the ajax still works

UHF-X Select 2 icons missing JSON path

---

composer.json

Prevent from updating to RC1 until it can be tested properly

UHF-X gin force beta5 version

---

hdbt_admin.theme

* Removed icons_path variable which seemed to be obsolete.

UHF-X Icons path fix

---

README.md

* Documentation was updated to include more information.
* https://github.com/City-of-Helsinki/drupal-hdbt/pull/684
* https://github.com/City-of-Helsinki/drupal-hdbt-admin/pull/221
* https://github.com/City-of-Helsinki/drupal-helfi-platform/pull/135
[UHF-4905]: https://helsinkisolutionoffice.atlassian.net/browse/UHF-4905?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

UHF-4905 hdbt documentation

---

dist/js/ckeditor-config.min.js
src/js/ckeditor-config.js

* Custom config for CKEditor
* Prevents `&nbsp;` on empty elements
* See the other referred Pull Request to complete the install
* [UHF-8503: CKEditor cleanup `platform-config`](https://github.com/City-of-Helsinki/drupal-helfi-platform-config/pull/549)
[UHF-8503]: https://helsinkisolutionoffice.atlassian.net/browse/UHF-8503?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

UHF-8503: CKEditor cleanup 

---

composer.json
dist/js/ckeditor-config.min.js
src/js/ckeditor-config.js

* Moved CKEditor config file under `hdbt_admin_tools` module
* https://github.com/City-of-Helsinki/drupal-hdbt-admin/pull/225
* https://github.com/City-of-Helsinki/drupal-helfi-platform-config/pull/553
[UHF-8503]: https://helsinkisolutionoffice.atlassian.net/browse/UHF-8503?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

UHF-8503: CKEditor cleanup (file moved)

---

package-lock.json
package.json

* Added caniuse update to package.json.
[UHF-9497]: https://helsinkisolutionoffice.atlassian.net/browse/UHF-9497?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

UHF-9497: Added caniuse update to package.json.

---

composer.json
hdbt_admin.theme
templates/navigation/links--language-block.html.twig

* Removed `hdbt_admin_preprocess()` function and moved all language related template variables to more precise preprocess functions and use predefined language object when possible. 
* Converted the `links--language-block` language variables to match the new language object.
* `make fresh`
* `composer require drupal/hdbt:dev-UHF-8909 drupal/hdbt_admin:dev-UHF-8909 drupal/helfi_platform_config:dev-UHF-8909`
* https://github.com/City-of-Helsinki/drupal-module-helfi-api-base/pull/173
* https://github.com/City-of-Helsinki/drupal-hdbt/pull/1028
* https://github.com/City-of-Helsinki/drupal-helfi-kymp/pull/904
* …

UHF-8909 Preprocess function refactor

---

package-lock.json
package.json
webpack.config.js

* Updated sass version
* Make sure your instance is up and running on correct branch.
* `git checkout UHF-11458`
* `make fresh`
* `composer require drupal/hdbt_admin:dev-UHF-11458 `
* https://github.com/City-of-Helsinki/drupal-hdbt/pull/1317
* https://github.com/City-of-Helsinki/drupal-helfi-asuminen/pull/600
* https://github.com/City-of-Helsinki/drupal-helfi-kymp/pull/1131
* https://github.com/City-of-Helsinki/drupal-helfi-tyo-yrittaminen/pull/589
* https://github.com/City-of-Helsinki/drupal-helfi-etusivu/pull/982
* https://github.com/City-of-Helsinki/drupal-helfi-kasvatus-koulutus/pull/887
* https://github.com/City-of-Helsinki/drupal-helfi-kuva/pull/539
* https://github.com/City-of-Helsinki/drupal-helfi-rekry/pull/760
* …

UHF-11458: Updated sass version to latest
